/*
 * FISSION
 * Easily use IPFS from Web 2.0 applications
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@fission.codes
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets Region
 */
@JsonAdapter(Region.Adapter.class)
public enum Region {
  
  CALIFORNIA("california"),
  
  DUBLIN("dublin"),
  
  FRANKFURT("frankfurt"),
  
  OREGON("oregon"),
  
  SINGAPORE("singapore"),
  
  SYDNEY("sydney"),
  
  TOKYO("tokyo"),
  
  VIRGINIA("virginia");

  private String value;

  Region(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Region fromValue(String text) {
    for (Region b : Region.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<Region> {
    @Override
    public void write(final JsonWriter jsonWriter, final Region enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Region read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Region.fromValue(String.valueOf(value));
    }
  }
}

