/*
 * FISSION
 * Easily use IPFS from Web 2.0 applications
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@fission.codes
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets Tier
 */
@JsonAdapter(Tier.Adapter.class)
public enum Tier {
  
  TEST("test"),
  
  FREE("free");

  private String value;

  Tier(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Tier fromValue(String text) {
    for (Tier b : Tier.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<Tier> {
    @Override
    public void write(final JsonWriter jsonWriter, final Tier enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Tier read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Tier.fromValue(String.valueOf(value));
    }
  }
}

