/*
 * FISSION
 * Easily use IPFS from Web 2.0 applications
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@fission.codes
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * UserConfig
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-24T18:30:18.655Z")
public class UserConfig {
  @SerializedName("INTERPLANETARY_FISSION_URL")
  private String INTERPLANETARY_FISSION_URL = null;

  @SerializedName("INTERPLANETARY_FISSION_USERNAME")
  private String INTERPLANETARY_FISSION_USERNAME = null;

  @SerializedName("INTERPLANETARY_FISSION_PASSWORD")
  private String INTERPLANETARY_FISSION_PASSWORD = null;

  public UserConfig INTERPLANETARY_FISSION_URL(String INTERPLANETARY_FISSION_URL) {
    this.INTERPLANETARY_FISSION_URL = INTERPLANETARY_FISSION_URL;
    return this;
  }

   /**
   * Get INTERPLANETARY_FISSION_URL
   * @return INTERPLANETARY_FISSION_URL
  **/
  @ApiModelProperty(required = true, value = "")
  public String getINTERPLANETARYFISSIONURL() {
    return INTERPLANETARY_FISSION_URL;
  }

  public void setINTERPLANETARYFISSIONURL(String INTERPLANETARY_FISSION_URL) {
    this.INTERPLANETARY_FISSION_URL = INTERPLANETARY_FISSION_URL;
  }

  public UserConfig INTERPLANETARY_FISSION_USERNAME(String INTERPLANETARY_FISSION_USERNAME) {
    this.INTERPLANETARY_FISSION_USERNAME = INTERPLANETARY_FISSION_USERNAME;
    return this;
  }

   /**
   * Get INTERPLANETARY_FISSION_USERNAME
   * @return INTERPLANETARY_FISSION_USERNAME
  **/
  @ApiModelProperty(required = true, value = "")
  public String getINTERPLANETARYFISSIONUSERNAME() {
    return INTERPLANETARY_FISSION_USERNAME;
  }

  public void setINTERPLANETARYFISSIONUSERNAME(String INTERPLANETARY_FISSION_USERNAME) {
    this.INTERPLANETARY_FISSION_USERNAME = INTERPLANETARY_FISSION_USERNAME;
  }

  public UserConfig INTERPLANETARY_FISSION_PASSWORD(String INTERPLANETARY_FISSION_PASSWORD) {
    this.INTERPLANETARY_FISSION_PASSWORD = INTERPLANETARY_FISSION_PASSWORD;
    return this;
  }

   /**
   * Get INTERPLANETARY_FISSION_PASSWORD
   * @return INTERPLANETARY_FISSION_PASSWORD
  **/
  @ApiModelProperty(required = true, value = "")
  public String getINTERPLANETARYFISSIONPASSWORD() {
    return INTERPLANETARY_FISSION_PASSWORD;
  }

  public void setINTERPLANETARYFISSIONPASSWORD(String INTERPLANETARY_FISSION_PASSWORD) {
    this.INTERPLANETARY_FISSION_PASSWORD = INTERPLANETARY_FISSION_PASSWORD;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserConfig userConfig = (UserConfig) o;
    return Objects.equals(this.INTERPLANETARY_FISSION_URL, userConfig.INTERPLANETARY_FISSION_URL) &&
        Objects.equals(this.INTERPLANETARY_FISSION_USERNAME, userConfig.INTERPLANETARY_FISSION_USERNAME) &&
        Objects.equals(this.INTERPLANETARY_FISSION_PASSWORD, userConfig.INTERPLANETARY_FISSION_PASSWORD);
  }

  @Override
  public int hashCode() {
    return Objects.hash(INTERPLANETARY_FISSION_URL, INTERPLANETARY_FISSION_USERNAME, INTERPLANETARY_FISSION_PASSWORD);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserConfig {\n");
    
    sb.append("    INTERPLANETARY_FISSION_URL: ").append(toIndentedString(INTERPLANETARY_FISSION_URL)).append("\n");
    sb.append("    INTERPLANETARY_FISSION_USERNAME: ").append(toIndentedString(INTERPLANETARY_FISSION_USERNAME)).append("\n");
    sb.append("    INTERPLANETARY_FISSION_PASSWORD: ").append(toIndentedString(INTERPLANETARY_FISSION_PASSWORD)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

