# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FISSION.Model.ProvisionRequest do
  @moduledoc """
  Request from Heroku to provision a new user
  """

  @derive [Poison.Encoder]
  defstruct [
    :"callbackUrl",
    :"name",
    :"plan",
    :"region",
    :"uuid"
  ]

  @type t :: %__MODULE__{
    :"callbackUrl" => String.t,
    :"name" => String.t,
    :"plan" => Tier,
    :"region" => Region,
    :"uuid" => String
  }
end

defimpl Poison.Decoder, for: FISSION.Model.ProvisionRequest do
  import FISSION.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"plan", :struct, FISSION.Model.Tier, options)
    |> deserialize(:"region", :struct, FISSION.Model.Region, options)
  end
end

