# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FISSION.Model.UserConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"INTERPLANETARY_FISSION_URL",
    :"INTERPLANETARY_FISSION_USERNAME",
    :"INTERPLANETARY_FISSION_PASSWORD"
  ]

  @type t :: %__MODULE__{
    :"INTERPLANETARY_FISSION_URL" => String.t,
    :"INTERPLANETARY_FISSION_USERNAME" => String.t,
    :"INTERPLANETARY_FISSION_PASSWORD" => Secret
  }
end

defimpl Poison.Decoder, for: FISSION.Model.UserConfig do
  import FISSION.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"INTERPLANETARY_FISSION_PASSWORD", :struct, FISSION.Model.Secret, options)
  end
end

