/**
* FISSION
* Easily use IPFS from Web 2.0 applications
*
* OpenAPI spec version: 1.0.0
* Contact: support@fission.codes
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


import com.squareup.moshi.Json

/**
* 
* Values: test,free
*/
enum class Tier(val value: kotlin.String){

    @Json(name = "test") test("test"),

    @Json(name = "free") free("free");

}

