/**
 * FISSION's IPFS API
 * Easily use IPFS from Web 2.0 applications
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@fission.codes
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/UserConfig', 'model/UserID'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./UserConfig'), require('./UserID'));
  } else {
    // Browser globals (root is window)
    if (!root.FissionsIpfsApi) {
      root.FissionsIpfsApi = {};
    }
    root.FissionsIpfsApi.HerokuProvision = factory(root.FissionsIpfsApi.ApiClient, root.FissionsIpfsApi.UserConfig, root.FissionsIpfsApi.UserID);
  }
}(this, function(ApiClient, UserConfig, UserID) {
  'use strict';




  /**
   * The HerokuProvision model module.
   * @module model/HerokuProvision
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>HerokuProvision</code>.
   * @alias module:model/HerokuProvision
   * @class
   * @param id {module:model/UserID} 
   * @param config {module:model/UserConfig} 
   */
  var exports = function(id, config) {
    var _this = this;

    _this['id'] = id;
    _this['config'] = config;

  };

  /**
   * Constructs a <code>HerokuProvision</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HerokuProvision} obj Optional instance to populate.
   * @return {module:model/HerokuProvision} The populated <code>HerokuProvision</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = UserID.constructFromObject(data['id']);
      }
      if (data.hasOwnProperty('config')) {
        obj['config'] = UserConfig.constructFromObject(data['config']);
      }
      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/UserID} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {module:model/UserConfig} config
   */
  exports.prototype['config'] = undefined;
  /**
   * @member {String} message
   */
  exports.prototype['message'] = undefined;



  return exports;
}));


