/**
 * FISSION's IPFS API
 * Easily use IPFS from Web 2.0 applications
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@fission.codes
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FissionsIpfsApi) {
      root.FissionsIpfsApi = {};
    }
    root.FissionsIpfsApi.Region = factory(root.FissionsIpfsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class Region.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "california"
     * @const
     */
    "california": "california",
    /**
     * value: "dublin"
     * @const
     */
    "dublin": "dublin",
    /**
     * value: "frankfurt"
     * @const
     */
    "frankfurt": "frankfurt",
    /**
     * value: "oregon"
     * @const
     */
    "oregon": "oregon",
    /**
     * value: "singapore"
     * @const
     */
    "singapore": "singapore",
    /**
     * value: "sydney"
     * @const
     */
    "sydney": "sydney",
    /**
     * value: "tokyo"
     * @const
     */
    "tokyo": "tokyo",
    /**
     * value: "virginia"
     * @const
     */
    "virginia": "virginia"  };

  /**
   * Returns a <code>Region</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/Region} The enum <code>Region</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


