/**
 * FISSION's IPFS API
 * Easily use IPFS from Web 2.0 applications
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@fission.codes
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FissionsIpfsApi) {
      root.FissionsIpfsApi = {};
    }
    root.FissionsIpfsApi.SerializedFile = factory(root.FissionsIpfsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SerializedFile model module.
   * @module model/SerializedFile
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SerializedFile</code>.
   * @alias module:model/SerializedFile
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>SerializedFile</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SerializedFile} obj Optional instance to populate.
   * @return {module:model/SerializedFile} The populated <code>SerializedFile</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    return data;
  }




  return exports;
}));


