/**
 * FISSION's IPFS API
 * Easily use IPFS from Web 2.0 applications
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@fission.codes
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Secret'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Secret'));
  } else {
    // Browser globals (root is window)
    if (!root.FissionsIpfsApi) {
      root.FissionsIpfsApi = {};
    }
    root.FissionsIpfsApi.UserConfig = factory(root.FissionsIpfsApi.ApiClient, root.FissionsIpfsApi.Secret);
  }
}(this, function(ApiClient, Secret) {
  'use strict';




  /**
   * The UserConfig model module.
   * @module model/UserConfig
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>UserConfig</code>.
   * @alias module:model/UserConfig
   * @class
   * @param INTERPLANETARY_FISSION_URL {String} 
   * @param INTERPLANETARY_FISSION_USERNAME {String} 
   * @param INTERPLANETARY_FISSION_PASSWORD {module:model/Secret} 
   */
  var exports = function(INTERPLANETARY_FISSION_URL, INTERPLANETARY_FISSION_USERNAME, INTERPLANETARY_FISSION_PASSWORD) {
    var _this = this;

    _this['INTERPLANETARY_FISSION_URL'] = INTERPLANETARY_FISSION_URL;
    _this['INTERPLANETARY_FISSION_USERNAME'] = INTERPLANETARY_FISSION_USERNAME;
    _this['INTERPLANETARY_FISSION_PASSWORD'] = INTERPLANETARY_FISSION_PASSWORD;
  };

  /**
   * Constructs a <code>UserConfig</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserConfig} obj Optional instance to populate.
   * @return {module:model/UserConfig} The populated <code>UserConfig</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('INTERPLANETARY_FISSION_URL')) {
        obj['INTERPLANETARY_FISSION_URL'] = ApiClient.convertToType(data['INTERPLANETARY_FISSION_URL'], 'String');
      }
      if (data.hasOwnProperty('INTERPLANETARY_FISSION_USERNAME')) {
        obj['INTERPLANETARY_FISSION_USERNAME'] = ApiClient.convertToType(data['INTERPLANETARY_FISSION_USERNAME'], 'String');
      }
      if (data.hasOwnProperty('INTERPLANETARY_FISSION_PASSWORD')) {
        obj['INTERPLANETARY_FISSION_PASSWORD'] = Secret.constructFromObject(data['INTERPLANETARY_FISSION_PASSWORD']);
      }
    }
    return obj;
  }

  /**
   * @member {String} INTERPLANETARY_FISSION_URL
   */
  exports.prototype['INTERPLANETARY_FISSION_URL'] = undefined;
  /**
   * @member {String} INTERPLANETARY_FISSION_USERNAME
   */
  exports.prototype['INTERPLANETARY_FISSION_USERNAME'] = undefined;
  /**
   * @member {module:model/Secret} INTERPLANETARY_FISSION_PASSWORD
   */
  exports.prototype['INTERPLANETARY_FISSION_PASSWORD'] = undefined;



  return exports;
}));


