/* 
 * FISSION
 *
 * Easily use IPFS from Web 2.0 applications
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@fission.codes
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines Region
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum Region
    {
        
        /// <summary>
        /// Enum California for value: california
        /// </summary>
        [EnumMember(Value = "california")]
        California = 1,
        
        /// <summary>
        /// Enum Dublin for value: dublin
        /// </summary>
        [EnumMember(Value = "dublin")]
        Dublin = 2,
        
        /// <summary>
        /// Enum Frankfurt for value: frankfurt
        /// </summary>
        [EnumMember(Value = "frankfurt")]
        Frankfurt = 3,
        
        /// <summary>
        /// Enum Oregon for value: oregon
        /// </summary>
        [EnumMember(Value = "oregon")]
        Oregon = 4,
        
        /// <summary>
        /// Enum Singapore for value: singapore
        /// </summary>
        [EnumMember(Value = "singapore")]
        Singapore = 5,
        
        /// <summary>
        /// Enum Sydney for value: sydney
        /// </summary>
        [EnumMember(Value = "sydney")]
        Sydney = 6,
        
        /// <summary>
        /// Enum Tokyo for value: tokyo
        /// </summary>
        [EnumMember(Value = "tokyo")]
        Tokyo = 7,
        
        /// <summary>
        /// Enum Virginia for value: virginia
        /// </summary>
        [EnumMember(Value = "virginia")]
        Virginia = 8
    }

}
