=begin
#FISSION

#Easily use IPFS from Web 2.0 applications

OpenAPI spec version: 1.0.0
Contact: support@fission.codes
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.5

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::IPFSApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'IPFSApi' do
  before do
    # run before each test
    @instance = SwaggerClient::IPFSApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IPFSApi' do
    it 'should create an instance of IPFSApi' do
      expect(@instance).to be_instance_of(SwaggerClient::IPFSApi)
    end
  end

  # unit tests for ipfs_peers_get
  # @param [Hash] opts the optional parameters
  # @return [Array<IPFSPeer>]
  describe 'ipfs_peers_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for ipfs_post
  # @param file A file to upload (may also be multipart/form-data)
  # @param [Hash] opts the optional parameters
  # @return [IPFSAddress]
  describe 'ipfs_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
