=begin
#FISSION

#Easily use IPFS from Web 2.0 applications

OpenAPI spec version: 1.0.0
Contact: support@fission.codes
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.5

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::PingApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PingApi' do
  before do
    # run before each test
    @instance = SwaggerClient::PingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PingApi' do
    it 'should create an instance of PingApi' do
      expect(@instance).to be_instance_of(SwaggerClient::PingApi)
    end
  end

  # unit tests for ping_get
  # @param [Hash] opts the optional parameters
  # @return [Pong]
  describe 'ping_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
