# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FISSION.Api.Ping do
  @moduledoc """
  API calls for all endpoints tagged `Ping`.
  """

  alias FISSION.Connection
  import FISSION.RequestBuilder


  @doc """

  ## Parameters

  - connection (FISSION.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %FISSION.Model.Pong{}} on success
  {:error, info} on failure
  """
  @spec ping_get(Tesla.Env.client, keyword()) :: {:ok, FISSION.Model.Pong.t} | {:error, Tesla.Env.t}
  def ping_get(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/ping")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%FISSION.Model.Pong{})
  end
end
