/* 
 * FISSION
 *
 * Easily use IPFS from Web 2.0 applications
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@fission.codes
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserConfigTests
    {
        // TODO uncomment below to declare an instance variable for UserConfig
        //private UserConfig instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserConfig
            //instance = new UserConfig();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserConfig
        /// </summary>
        [Test]
        public void UserConfigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserConfig
            //Assert.IsInstanceOfType<UserConfig> (instance, "variable 'instance' is a UserConfig");
        }


        /// <summary>
        /// Test the property 'INTERPLANETARY_FISSION_URL'
        /// </summary>
        [Test]
        public void INTERPLANETARY_FISSION_URLTest()
        {
            // TODO unit test for the property 'INTERPLANETARY_FISSION_URL'
        }
        /// <summary>
        /// Test the property 'INTERPLANETARY_FISSION_USERNAME'
        /// </summary>
        [Test]
        public void INTERPLANETARY_FISSION_USERNAMETest()
        {
            // TODO unit test for the property 'INTERPLANETARY_FISSION_USERNAME'
        }
        /// <summary>
        /// Test the property 'INTERPLANETARY_FISSION_PASSWORD'
        /// </summary>
        [Test]
        public void INTERPLANETARY_FISSION_PASSWORDTest()
        {
            // TODO unit test for the property 'INTERPLANETARY_FISSION_PASSWORD'
        }

    }

}
