{-
   FISSION
   Easily use IPFS from Web 2.0 applications

   OpenAPI spec version: 1.0.0
   Contact: support@fission.codes

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.ProvisionRequest exposing (ProvisionRequest, provisionRequestDecoder, provisionRequestEncoder)

import Data.Tier exposing (Tier, tierDecoder, tierEncoder)
import Data.Region exposing (Region, regionDecoder, regionEncoder)
import Data.UUID exposing (UUID, uUIDDecoder, uUIDEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   Request from Heroku to provision a new user
-}


type alias ProvisionRequest =
    { callbackUrl : String
    , name : String
    , plan : Tier
    , region : Region
    , uuid : UUID
    }


provisionRequestDecoder : Decoder ProvisionRequest
provisionRequestDecoder =
    decode ProvisionRequest
        |> required "callbackUrl" Decode.string
        |> required "name" Decode.string
        |> required "plan" tierDecoder
        |> required "region" regionDecoder
        |> required "uuid" uUIDDecoder



provisionRequestEncoder : ProvisionRequest -> Encode.Value
provisionRequestEncoder model =
    Encode.object
        [ ( "callbackUrl", Encode.string model.callbackUrl )
        , ( "name", Encode.string model.name )
        , ( "plan", tierEncoder model.plan )
        , ( "region", regionEncoder model.region )
        , ( "uuid", uUIDEncoder model.uuid )
        ]


