{-
   FISSION
   Easily use IPFS from Web 2.0 applications

   OpenAPI spec version: 1.0.0
   Contact: support@fission.codes

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.Serialized File exposing (Serialized File, serialized FileDecoder, serialized FileEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)




type alias Serialized File
    = String


serialized FileDecoder : Decoder Serialized File
serialized FileDecoder =
    Decode.string


serialized FileEncoder : Serialized File -> Encode.Value
serialized FileEncoder =
    Encode.string
