{-
   FISSION
   Easily use IPFS from Web 2.0 applications

   OpenAPI spec version: 1.0.0
   Contact: support@fission.codes

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.UserConfig exposing (UserConfig, userConfigDecoder, userConfigEncoder)

import Data.Secret exposing (Secret, secretDecoder, secretEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)




type alias UserConfig =
    { iNTERPLANETARYFISSIONURL : String
    , iNTERPLANETARYFISSIONUSERNAME : String
    , iNTERPLANETARYFISSIONPASSWORD : Secret
    }


userConfigDecoder : Decoder UserConfig
userConfigDecoder =
    decode UserConfig
        |> required "INTERPLANETARY_FISSION_URL" Decode.string
        |> required "INTERPLANETARY_FISSION_USERNAME" Decode.string
        |> required "INTERPLANETARY_FISSION_PASSWORD" secretDecoder



userConfigEncoder : UserConfig -> Encode.Value
userConfigEncoder model =
    Encode.object
        [ ( "INTERPLANETARY_FISSION_URL", Encode.string model.iNTERPLANETARYFISSIONURL )
        , ( "INTERPLANETARY_FISSION_USERNAME", Encode.string model.iNTERPLANETARYFISSIONUSERNAME )
        , ( "INTERPLANETARY_FISSION_PASSWORD", secretEncoder model.iNTERPLANETARYFISSIONPASSWORD )
        ]


