//
// ProvisionRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Request from Heroku to provision a new user */

public struct ProvisionRequest: Codable {

    public var callbackUrl: String
    public var name: String
    public var plan: Tier
    public var region: Region
    public var uuid: UUID

    public init(callbackUrl: String, name: String, plan: Tier, region: Region, uuid: UUID) {
        self.callbackUrl = callbackUrl
        self.name = name
        self.plan = plan
        self.region = region
        self.uuid = uuid
    }


}

