//
// Region.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum Region: String, Codable {
    case california = "california"
    case dublin = "dublin"
    case frankfurt = "frankfurt"
    case oregon = "oregon"
    case singapore = "singapore"
    case sydney = "sydney"
    case tokyo = "tokyo"
    case virginia = "virginia"

}
