//
// Tier.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum Tier: String, Codable {
    case test = "test"
    case free = "free"

}
