//
// UserConfig.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserConfig: Codable {

    public var INTERPLANETARY_FISSION_URL: String
    public var INTERPLANETARY_FISSION_USERNAME: String
    public var INTERPLANETARY_FISSION_PASSWORD: Secret

    public init(INTERPLANETARY_FISSION_URL: String, INTERPLANETARY_FISSION_USERNAME: String, INTERPLANETARY_FISSION_PASSWORD: Secret) {
        self.INTERPLANETARY_FISSION_URL = INTERPLANETARY_FISSION_URL
        self.INTERPLANETARY_FISSION_USERNAME = INTERPLANETARY_FISSION_USERNAME
        self.INTERPLANETARY_FISSION_PASSWORD = INTERPLANETARY_FISSION_PASSWORD
    }


}

