{-
   FISSION
   Easily use IPFS from Web 2.0 applications

   OpenAPI spec version: 1.0.0
   Contact: support@fission.codes

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Request.Heroku exposing (herokuResourcesPost)

import Data.HerokuProvision exposing (HerokuProvision, herokuProvisionDecoder)
import Data.ProvisionRequest exposing (ProvisionRequest, provisionRequestEncoder)
import Http
import Json.Decode as Decode


basePath : String
basePath =
    "https://hostless.dev"


{-
   
-}
herokuResourcesPost : ProvisionRequest -> Http.Request HerokuProvision
herokuResourcesPost model =
    { method = "POST"
    , url = basePath ++ "/heroku/resources"
    , headers = []
    , body = Http.jsonBody <| provisionRequestEncoder model
    , expect = Http.expectJson herokuProvisionDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


