{-
   FISSION
   Easily use IPFS from Web 2.0 applications

   OpenAPI spec version: 1.0.0
   Contact: support@fission.codes

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Request.IPFS exposing (ipfsPeersGet, ipfsPost)

import Data.IPFSAddress exposing (IPFSAddress, iPFSAddressDecoder)
import Data.IPFSPeer exposing (IPFSPeer, iPFSPeerDecoder)
import Http
import Json.Decode as Decode


basePath : String
basePath =
    "https://hostless.dev"


{-
   
-}
ipfsPeersGet : Http.Request (List IPFSPeer)
ipfsPeersGet =
    { method = "GET"
    , url = basePath ++ "/ipfs/peers"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson (Decode.list iPFSPeerDecoder)
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   
-}
ipfsPost : Http.Request IPFSAddress
ipfsPost =
    { method = "POST"
    , url = basePath ++ "/ipfs"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson iPFSAddressDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


