{-
   FISSION
   Easily use IPFS from Web 2.0 applications

   OpenAPI spec version: 1.0.0
   Contact: support@fission.codes

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Request.Ping exposing (pingGet)

import Data.Pong exposing (Pong, pongDecoder)
import Http
import Json.Decode as Decode


basePath : String
basePath =
    "https://hostless.dev"


{-
   
-}
pingGet : Http.Request Pong
pingGet =
    { method = "GET"
    , url = basePath ++ "/ping"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson pongDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


