/**
 * FISSION's IPFS API
 * Easily use IPFS from Web 2.0 applications
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@fission.codes
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/IPFSAddress', 'model/IPFSPeer'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/IPFSAddress'), require('../model/IPFSPeer'));
  } else {
    // Browser globals (root is window)
    if (!root.FissionsIpfsApi) {
      root.FissionsIpfsApi = {};
    }
    root.FissionsIpfsApi.IPFSApi = factory(root.FissionsIpfsApi.ApiClient, root.FissionsIpfsApi.IPFSAddress, root.FissionsIpfsApi.IPFSPeer);
  }
}(this, function(ApiClient, IPFSAddress, IPFSPeer) {
  'use strict';

  /**
   * IPFS service.
   * @module api/IPFSApi
   * @version 1.0.0
   */

  /**
   * Constructs a new IPFSApi. 
   * @alias module:api/IPFSApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the ipfsPeersGet operation.
     * @callback module:api/IPFSApi~ipfsPeersGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/IPFSPeer>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/IPFSApi~ipfsPeersGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/IPFSPeer>}
     */
    this.ipfsPeersGet = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json;charset=utf-8'];
      var returnType = [IPFSPeer];

      return this.apiClient.callApi(
        '/ipfs/peers', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ipfsPost operation.
     * @callback module:api/IPFSApi~ipfsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/IPFSAddress} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} file A file to upload (may also be multipart/form-data)
     * @param {module:api/IPFSApi~ipfsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/IPFSAddress}
     */
    this.ipfsPost = function(file, callback) {
      var postBody = null;

      // verify the required parameter 'file' is set
      if (file === undefined || file === null) {
        throw new Error("Missing the required parameter 'file' when calling ipfsPost");
      }


      var pathParams = {
      };
      var queryParams = {
        'file': file,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['multipart/form-data'];
      var accepts = ['application/octet-stream', 'text/plain;charset=utf-8'];
      var returnType = IPFSAddress;

      return this.apiClient.callApi(
        '/ipfs', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
