<?php
/**
 * UserConfigTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FISSION
 *
 * Easily use IPFS from Web 2.0 applications
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@fission.codes
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UserConfigTest Class Doc Comment
 *
 * @category    Class
 * @description UserConfig
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserConfigTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UserConfig"
     */
    public function testUserConfig()
    {
    }

    /**
     * Test attribute "interplanetary_fission_url"
     */
    public function testPropertyInterplanetaryFissionUrl()
    {
    }

    /**
     * Test attribute "interplanetary_fission_username"
     */
    public function testPropertyInterplanetaryFissionUsername()
    {
    }

    /**
     * Test attribute "interplanetary_fission_password"
     */
    public function testPropertyInterplanetaryFissionPassword()
    {
    }
}
