<?php
/**
 * Region
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FISSION
 *
 * Easily use IPFS from Web 2.0 applications
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@fission.codes
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * Region Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Region
{
    /**
     * Possible values of this enum
     */
    const CALIFORNIA = 'california';
    const DUBLIN = 'dublin';
    const FRANKFURT = 'frankfurt';
    const OREGON = 'oregon';
    const SINGAPORE = 'singapore';
    const SYDNEY = 'sydney';
    const TOKYO = 'tokyo';
    const VIRGINIA = 'virginia';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CALIFORNIA,
            self::DUBLIN,
            self::FRANKFURT,
            self::OREGON,
            self::SINGAPORE,
            self::SYDNEY,
            self::TOKYO,
            self::VIRGINIA,
        ];
    }
}


