/*
 * FISSION
 *
 * Easily use IPFS from Web 2.0 applications
 *
 * API version: 1.0.0
 * Contact: support@fission.codes
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Tier string

// List of Tier
const (
	TEST_Tier Tier = "test"
	FREE_Tier Tier = "free"
)
