/*
 * FISSION
 *
 * Easily use IPFS from Web 2.0 applications
 *
 * API version: 1.0.0
 * Contact: support@fission.codes
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Region string

// List of Region
const (
	CALIFORNIA_Region Region = "california"
	DUBLIN_Region Region = "dublin"
	FRANKFURT_Region Region = "frankfurt"
	OREGON_Region Region = "oregon"
	SINGAPORE_Region Region = "singapore"
	SYDNEY_Region Region = "sydney"
	TOKYO_Region Region = "tokyo"
	VIRGINIA_Region Region = "virginia"
)
