/*
 * FISSION
 *
 * Easily use IPFS from Web 2.0 applications
 *
 * API version: 1.0.0
 * Contact: support@fission.codes
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SerializedFile struct {
}
