/*
 * FISSION
 *
 * Easily use IPFS from Web 2.0 applications
 *
 * API version: 1.0.0
 * Contact: support@fission.codes
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Request from Heroku to provision a new user
type ProvisionRequest struct {
	CallbackUrl string `json:"callbackUrl"`
	Name string `json:"name"`
	Plan *Tier `json:"plan"`
	Region *Region `json:"region"`
	Uuid string `json:"uuid"`
}
