/*
 * FISSION
 *
 * Easily use IPFS from Web 2.0 applications
 *
 * API version: 1.0.0
 * Contact: support@fission.codes
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HerokuProvision struct {
	Id *UserId `json:"id"`
	Config *UserConfig `json:"config"`
	Message string `json:"message,omitempty"`
}
