/* 
 * FISSION
 *
 * Easily use IPFS from Web 2.0 applications
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@fission.codes
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HerokuApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class HerokuApiTests
    {
        private HerokuApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new HerokuApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HerokuApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' HerokuApi
            //Assert.IsInstanceOfType(typeof(HerokuApi), instance, "instance is a HerokuApi");
        }

        
        /// <summary>
        /// Test HerokuResourcesPost
        /// </summary>
        [Test]
        public void HerokuResourcesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProvisionRequest body = null;
            //var response = instance.HerokuResourcesPost(body);
            //Assert.IsInstanceOf<HerokuProvision> (response, "response is HerokuProvision");
        }
        
    }

}
