/* 
 * FISSION
 *
 * Easily use IPFS from Web 2.0 applications
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@fission.codes
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Region {
}

impl Region {
  pub fn new() -> Region {
    Region {
    }
  }

}

// TODO enum 
// List of Region
//const (
//  
//  
//  
//)


