/**
 * FISSION
 * Easily use IPFS from Web 2.0 applications
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@fission.codes
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import java.util.UUID

case class ProvisionRequest (
  callbackUrl: String,
  name: String,
  plan: Tier,
  region: Region,
  uuid: UUID
)

