=begin
#FISSION

#Easily use IPFS from Web 2.0 applications

OpenAPI spec version: 1.0.0
Contact: support@fission.codes
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.5

=end

require 'date'

module SwaggerClient
  class Tier
    
    TEST = 'test'.freeze
    FREE = 'free'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = Tier.constants.select { |c| Tier::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #Tier" if constantValues.empty?
      value
    end
  end
end
