/**
 * FISSION
 * Easily use IPFS from Web 2.0 applications
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@fission.codes
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export enum Region {
    California = <any> 'california',
    Dublin = <any> 'dublin',
    Frankfurt = <any> 'frankfurt',
    Oregon = <any> 'oregon',
    Singapore = <any> 'singapore',
    Sydney = <any> 'sydney',
    Tokyo = <any> 'tokyo',
    Virginia = <any> 'virginia'
}
