/**
 * FISSION
 * Easily use IPFS from Web 2.0 applications
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@fission.codes
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface UserConfig {
    INTERPLANETARY_FISSION_URL: string;

    INTERPLANETARY_FISSION_USERNAME: string;

    INTERPLANETARY_FISSION_PASSWORD: models.Secret;

}
