=begin
#FISSION

#Easily use IPFS from Web 2.0 applications

OpenAPI spec version: 1.0.0
Contact: support@fission.codes
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.5

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/heroku_provision'
require 'swagger_client/models/ipfs_address'
require 'swagger_client/models/ipfs_peer'
require 'swagger_client/models/pong'
require 'swagger_client/models/provision_request'
require 'swagger_client/models/region'
require 'swagger_client/models/secret'
require 'swagger_client/models/serialized_file'
require 'swagger_client/models/tier'
require 'swagger_client/models/uuid'
require 'swagger_client/models/user_config'
require 'swagger_client/models/user_id'

# APIs
require 'swagger_client/api/heroku_api'
require 'swagger_client/api/ipfs_api'
require 'swagger_client/api/ping_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
