/*
 * FISSION
 * Easily use IPFS from Web 2.0 applications
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@fission.codes
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.HerokuProvision;
import io.swagger.client.model.ProvisionRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HerokuApi
 */
@Ignore
public class HerokuApiTest {

    private final HerokuApi api = new HerokuApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void herokuResourcesPostTest() throws ApiException {
        ProvisionRequest body = null;
        HerokuProvision response = api.herokuResourcesPost(body);

        // TODO: test validations
    }
    
}
