# coding: utf-8

"""
    FISSION

    Easily use IPFS from Web 2.0 applications  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@fission.codes
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.heroku_api import HerokuApi  # noqa: E501
from swagger_client.rest import ApiException


class TestHerokuApi(unittest.TestCase):
    """HerokuApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.heroku_api.HerokuApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_heroku_resources_post(self):
        """Test case for heroku_resources_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
