# coding: utf-8

"""
    FISSION

    Easily use IPFS from Web 2.0 applications  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@fission.codes
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.user_id import UserID  # noqa: E501
from swagger_client.rest import ApiException


class TestUserID(unittest.TestCase):
    """UserID unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserID(self):
        """Test UserID"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_id.UserID()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
