//
// IPFSAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class IPFSAPI {
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func ipfsPeersGet(completion: @escaping ((_ data: [IPFSPeer]?,_ error: Error?) -> Void)) {
        ipfsPeersGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /ipfs/peers
     - examples: [{contentType=application/json;charset=utf-8, example=[ "/ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd", "/ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd" ]}]

     - returns: RequestBuilder<[IPFSPeer]> 
     */
    open class func ipfsPeersGetWithRequestBuilder() -> RequestBuilder<[IPFSPeer]> {
        let path = "/ipfs/peers"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[IPFSPeer]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter file: (query) A file to upload (may also be multipart/form-data) 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func ipfsPost(file: String, completion: @escaping ((_ data: IPFSAddress?,_ error: Error?) -> Void)) {
        ipfsPostWithRequestBuilder(file: file).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /ipfs
     - examples: [{output=none}]
     
     - parameter file: (query) A file to upload (may also be multipart/form-data) 

     - returns: RequestBuilder<IPFSAddress> 
     */
    open class func ipfsPostWithRequestBuilder(file: String) -> RequestBuilder<IPFSAddress> {
        let path = "/ipfs"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "file": file
        ])

        let requestBuilder: RequestBuilder<IPFSAddress>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
